### PR TITLE
add zero shot classification task

### PR DESCRIPTION
**Pull request by TristanThrush**
This PR adds zero shot classification, and should be merged along with this PR: https://github.com/huggingface/autonlp-backend/pull/681

### CODE REVIEW

**Review by lewtun — APPROVED** [review]
Thanks a lot for adding this new task @TristanThrush ! 

The code LGTM, but could you please share a screenshot of the new UI to be sure it works when we merge?

Also, you'll need to fix the code style issues with `make style`

I suggest we merge this once the AutoTrain PR has been merged

**Review by lewtun — APPROVED** [review]
Thanks for iterating and refactoring this @mathemakitten 🔥 !

There's just one small change and then this looks good to merge. We should wait until the AutoTrain feature is deployed before merging though

**Comment by lewtun** [comment]
Oh, one thing that occurred to me: we'll need to have a special AutoTrain payload to specify the hardware for this task. We should definitely include that in this PR once that feature is implemented in AutoTrain

**Comment by lewtun** [comment]
@mathemakitten now that https://github.com/huggingface/autotrain-backend/pull/681 has been merged, WDYT about giving this feature a test run with a small model / dataset that can run on the default AutoTrain GPUs?

**Comment by mathemakitten** [comment]
Ran this successfully with Autotrain main commit `9a81e379363ae3d9fade37491b15185c3da93e7f` (Sept 8), results [here](https://huggingface.co/autoevaluate/zero-shot-classification/blob/refs%2Fpr%2F3/README.md). 

Will add a modification to the payload shortly, then I think we're good to go!

**Pull request merged**
